#%RAML 1.0
---

title: Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Error Codes
    content: !include docs/error_codes.md

traits:
  contentType:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
  testScenarioHeader:
    headers:
      Gov-Test-Scenario:
        description: See Test Data table for all header values.
        type: string
        required: false
        example: '-'
  agentSubscription:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              failedRequest:
                description: Invalid POST/PUT request by an agent who is not authorized by client
                value:
                  code: INVALID_REQUEST
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              agentNotSubscribed:
                description: Agent not subscribed to Agent Services
                value:
                  code: AGENT_NOT_SUBSCRIBED
              agentNotAuthorized:
                description: GET request by an agent who is not authorized by client
                value:
                  code: AGENT_NOT_AUTHORIZED
  clientSubscriptionToMTD:
      responses:
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                clientNotSubscribedToMTD:
                  description: Client not subscribed to MTD
                  value:
                    code: CLIENT_NOT_SUBSCRIBED
  overlappingPeriod:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              overlappingPeriod:
                description: A period cannot overlap with another period
                value:
                  code: OVERLAPPING_PERIOD

/self-assessment:
  /ni/{nino}:
    uriParameters:
      nino:
        description: National Insurance Number
        type: string
    /self-employments:
      (annotations.group):
          name: Self-employment business
          description: !include docs/self-employment.md
      post:
        displayName: Add a self-employment business
        description: Add a self-employment business
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "write:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
        body:
          application/json:
            type: !include schemas/SelfEmployment_Create_Without_ID.json
            example: !include examples/self-employment/SelfEmploymentCreate.json
        responses:
          201:
            headers:
              Location:
                example: /self-assessment/ni/{nino}/self-employments/{selfEmploymentId}
                description: Location of the resource created
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
                  mandatoryField:
                    description: Mandatory field missing
                    value:
                      code: MANDATORY_FIELD_MISSING
                  invalidDate:
                    description: Non ISO format date
                    value:
                      code: INVALID_DATE
                  commencementDateInThePast:
                    description: commencementDate not in past
                    value:
                      code: DATE_NOT_IN_THE_PAST
                  startDateInvalid:
                    description: Invalid start date
                    value:
                      code: START_DATE_INVALID
                  invalidAccountingPeriod:
                    description: Accounting period end is after start
                    value:
                      code: INVALID_ACCOUNTING_PERIOD
                  invalidValue:
                    description: Invalid accounting type
                    value:
                      code: INVALID_VALUE
                  invalidFieldLength:
                    description: Invalid field length
                    value:
                      code: INVALID_FIELD_LENGTH
                  invalidBusinessDescription:
                    description: Invalid business description
                    value:
                      code: INVALID_BUSINESS_DESCRIPTION
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  tooManySources:
                    description: Adding 2nd SE business
                    value:
                      code: TOO_MANY_SOURCES
      get:
        displayName: List all self-employment businesses
        description: List all self-employment businesses
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "read:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include schemas/SelfEmployments.json
                example: !include examples/self-employment/SelfEmployments.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
      /{selfEmploymentId}:
        description: Self-employment business
        uriParameters:
          selfEmploymentId:
            displayName: Self-employment ID
            description: An identifier for the self-employment business, unique to the customer
            type: string
        get:
          displayName: Get a self-employment business
          description: Get a self-employment business
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/SelfEmployment_Without_ID.json
                  example: !include examples/self-employment/SelfEmployment.json
            400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
            404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
        /obligations:
          get:
            displayName: Retrieve UK self employment business obligations
            description: Retrieve UK self employment business obligations
            (annotations.sandboxData): !include scenarios/self-employment-obligation-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/Obligations.json
                    example: !include examples/Obligations.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
        /periods:
          post:
            displayName: Create a self-employment period
            description: Create a self-employment period for submission of periodic data i.e incomes and expenses
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/SE_Period_Without_ID.json
                example: !include examples/self-employment/Period.json
            responses:
              201:
                headers:
                  Location:
                    example: /self-assessment/ni/{nino}/self-employments/{selfEmploymentId}/periods/{periodId}
                    description: Location of the resource created
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      mandatoryField:
                        description: Mandatory field missing (from and to fields)
                        value:
                          code: MANDATORY_FIELD_MISSING
                      invalidDate:
                        description: Non ISO format date (from and to fields)
                        value:
                          code: INVALID_DATE
                      invalidPeriod:
                        description: from is not <= to
                        value:
                          code: INVALID_PERIOD
                      invalidMonetaryAmount:
                        description: income or expense is not a non-negative amount or up to 2 decimal places
                        value:
                          code: INVALID_MONETARY_AMOUNT
                      invalidDisallowableAmount:
                        description: disallowableAmount > amount (except for depreciation expenseType)
                        value:
                          code: INVALID_DISALLOWABLE_AMOUNT
                      depreciationDisallowableAmount:
                        description: disallowableAmount != amount (for depreciation expenseType)
                        value:
                          code: DEPRECIATION_DISALLOWABLE_AMOUNT
              403:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidPeriod:
                        description: If periods are not contiguous
                        value:
                          code: INVALID_PERIOD
          get:
            displayName: List all self-employment periods
            description: List all self-employment periods
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/Periods.json
                    example: !include examples/Periods.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
          /{periodId}:
            uriParameters:
              periodId:
                description: An identifier for the period
                type: string
            get:
              displayName: Get a self-employment periodic summary
              description: Get a single self-employment periodic summary for a given identifier
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      type: !include schemas/SE_Period_Without_ID.json
                      example: !include examples/self-employment/Period.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
            put:
              displayName: Update a self-employment periodic summary
              description: Update a self-employment periodic summary
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/SE_UpdatePeriod.json
                  example: !include examples/self-employment/UpdatePeriod.json
              responses:
                204:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidDisallowableAmount:
                          description: disallowableAmount > amount (except for depreciation expenseType)
                          value:
                            code: INVALID_DISALLOWABLE_AMOUNT
                        depreciationDisallowableAmount:
                          description: disallowableAmount != amount (for depreciation expenseType)
                          value:
                            code: DEPRECIATION_DISALLOWABLE_AMOUNT
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
        /{taxYear}:
          uriParameters:
            taxYear:
              description: The tax year the data applies to
              type: string
              example: 2016-17
          put:
            displayName: Update a self-employment annual summary
            description: Update a self-employment annual summary for a tax year
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/SE_AnnualSummary.json
                example: !include examples/self-employment/AnnualSummary.json
            responses:
              204:
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      invalidTaxYear:
                        description: Invalid taxYear
                        value:
                          code: TAX_YEAR_INVALID
                      mandatoryField:
                        description: Mandatory field missing (from and to fields)
                        value:
                          code: MANDATORY_FIELD_MISSING
                      invalidMonetaryAmount1:
                        description: valid non-negative amount not provided where expected (except averagingAdjustment and basisAdjustment)
                        value:
                          code: INVALID_MONETARY_AMOUNT
                      invalidMonetaryAmount2:
                        description: valid amount not provided where expected (for averagingAdjustment and basisAdjustment)
                        value:
                          code: INVALID_MONETARY_AMOUNT
                      invalidBalancingChargeBPRA:
                        description: Balancing charge on sale or cessation of business use (Box 58) can only have a value > 0 in if BPRA (Box 54) is also > 0
                        value:
                          code: INVALID_BALANCING_CHARGE_BPRA
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
          get:
            displayName: Get a self-employment annual summary
            description: Get a self-employment annual summary for a tax year
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/SE_AnnualSummary.json
                    example: !include examples/self-employment/AnnualSummary.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      invalidTaxYear:
                        description: Invalid taxYear
                        value:
                          code: TAX_YEAR_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
    /uk-properties:
      (annotations.group):
        name: UK property business
        description: !include docs/uk-property.md
      post:
        displayName: Add a UK property business
        description: Add a UK property business
        is: [headers.acceptHeader, contentType, clientSubscriptionToMTD, agentSubscription]
        (annotations.scope): "write:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
        body:
          application/json:
            type: !include schemas/UkProperties.json
            example: !include examples/uk-properties/UkProperties.json
        responses:
          201:
            headers:
              Location:
                example: /self-assessment/ni/{nino}/uk-properties
                description: Location of the resource created
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
                  invalidValue:
                    description: Invalid accounting type
                    value:
                      code: INVALID_VALUE
          409:
            headers:
              Location:
                example: /self-assessment/ni/{nino}/uk-properties
            body:
              application/json:
                type: !include schemas/Error.json
                example: !include examples/errors/CONFLICT.json
      get:
        displayName: Get a UK property business
        description: Get a UK property business
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "read:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include schemas/UkProperties.json
                example: !include examples/uk-properties/UkProperties.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  notFound:
                    description: Not Found
                    value:
                      code: NOT_FOUND
      put:
        displayName: Update a UK property business
        description: Update a UK property business
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "write:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
        body:
          application/json:
            type: !include schemas/UkProperties.json
            example: !include examples/uk-properties/UkProperties.json
        responses:
          204:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
                  invalidValue:
                    description: Invalid accounting type
                    value:
                      code: INVALID_VALUE
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  notFound:
                    description: Not Found
                    value:
                      code: NOT_FOUND
      /obligations:
        get:
          displayName: Retrieve all UK property business obligations
          description: Retrieve all UK property business obligations
          (annotations.sandboxData): !include scenarios/property-obligation-scenarios.md
          is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/Obligations.json
                  example: !include examples/Obligations.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: Not Found
                      value:
                        code: NOT_FOUND
      /other:
        /periods:
          post:
            displayName: Create a non FHL UK property period
            description: Create a non FHL UK property period for submission of periodic data i.e incomes and expenses
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, overlappingPeriod]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/UK_PROP_OTHER_Period_Without_ID.json
                example: !include examples/uk-properties/other/Period.json
            responses:
              201:
                headers:
                  Location:
                    example: /self-assessment/ni/{nino}/uk-properties/{propertyType}/periods/{periodId}
                    description: Location of the resource created
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      mandatoryField:
                        description: Mandatory field missing (from and to fields)
                        value:
                          code: MANDATORY_FIELD_MISSING
                      invalidDate:
                        description: Non ISO format date (from and to fields)
                        value:
                          code: INVALID_DATE
                      invalidPeriod:
                        description: from is not <= to
                        value:
                          code: INVALID_PERIOD
                      invalidMonetaryAmount:
                        description: income or expense is not a non-negative amount or up to 2 decimal places
                        value:
                          code: INVALID_MONETARY_AMOUNT
              409:
                body:
                  application/json:
                    type: !include schemas/Error.json
                    example: !include examples/errors/CONFLICT.json
          get:
            displayName: List all non FHL UK property periods
            description: List all non FHL UK property periods
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/Periods.json
                    example: !include examples/Periods.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
          /{periodId}:
            uriParameters:
              periodId:
                displayName: Period ID
                type: string
            get:
              displayName: Get a non FHL UK property periodic summary
              description: Get a non FHL UK property periodic summary for a given identifier
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      type: !include schemas/UK_PROP_OTHER_Period_Without_ID.json
                      example: !include examples/uk-properties/other/Period.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
            put:
              displayName: Update a non FHL UK property periodic summary
              description: Update a non FHL UK property periodic summary
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/UK_PROP_OTHER_UpdatePeriod.json
                  example: !include examples/uk-properties/other/UpdatePeriod.json
              responses:
                204:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidMonetaryAmount:
                          description: income or expense is not a non-negative amount or up to 2 decimal places
                          value:
                            code: INVALID_MONETARY_AMOUNT
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
        /{taxYear}:
            displayName: Annual Summary
            uriParameters:
              taxYear:
                description: The tax year the data applies to
                type: string
                example: 2016-17
            put:
              displayName: Update a non-FHL UK property business annual summary
              description: Update a non-FHL UK property business annual summary for a tax year
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/UK_PROP_OTHER_AnnualSummary.json
                  example: !include examples/uk-properties/other/AnnualSummary.json
              responses:
                204:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidTaxYear:
                          description: Invalid taxYear
                          value:
                            code: TAX_YEAR_INVALID
                        invalidMonetaryAmount:
                          description: adjustments or allowances is not a non-negative amount or up to 2 decimal places
                          value:
                            code: INVALID_MONETARY_AMOUNT
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
            get:
              displayName: Get non FHL UK property business annual summary
              description: Get non FHL UK property business for a tax year
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      type: !include schemas/UK_PROP_OTHER_AnnualSummary.json
                      example: !include examples/uk-properties/other/AnnualSummary.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidTaxYear:
                          description: Invalid taxYear
                          value:
                            code: TAX_YEAR_INVALID
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
      /furnished-holiday-lettings:
        /periods:
          post:
            displayName: Create a FHL UK property period
            description: Create a FHL UK property period for submission of periodic data i.e incomes and expenses
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, overlappingPeriod]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/UK_PROP_FHL_Period_Without_ID.json
                example: !include examples/uk-properties/fhl/Period.json
            responses:
              201:
                headers:
                  Location:
                    example: /self-assessment/ni/{nino}/uk-properties/{propertyType}/periods/{periodId}
                    description: Location of the resource created
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      mandatoryField:
                        description: Mandatory field missing (from and to fields)
                        value:
                          code: MANDATORY_FIELD_MISSING
                      invalidDate:
                        description: Non ISO format date (from and to fields)
                        value:
                          code: INVALID_DATE
                      invalidPeriod:
                        description: from is not <= to
                        value:
                          code: INVALID_PERIOD
                      invalidMonetaryAmount:
                        description: income or expense is not a non-negative amount or up to 2 decimal places
                        value:
                          code: INVALID_MONETARY_AMOUNT
              409:
                body:
                  application/json:
                    type: !include schemas/Error.json
                    example: !include examples/errors/CONFLICT.json
          get:
            displayName: List all FHL UK property periods
            description: List all FHL UK property periods
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/Periods.json
                    example: !include examples/Periods.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
          /{periodId}:
            uriParameters:
              periodId:
                displayName: Period ID
                type: string
            get:
              displayName: Get a FHL UK property periodic summary
              description: Get a FHL UK property periodic summary for a given identifier
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      type: !include schemas/UK_PROP_FHL_Period_Without_ID.json
                      example: !include examples/uk-properties/fhl/Period.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
            put:
              displayName: Update a FHL UK property periodic summary
              description: Update a FHL UK property periodic summary
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/UK_PROP_FHL_UpdatePeriod.json
                  example: !include examples/uk-properties/fhl/UpdatePeriod.json
              responses:
                204:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidTaxYear:
                          description: Invalid taxYear
                          value:
                            code: TAX_YEAR_INVALID
                        invalidMonetaryAmount:
                          description: adjustments or allowances is not a non-negative amount or up to 2 decimal places
                          value:
                            code: INVALID_MONETARY_AMOUNT
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
        /{taxYear}:
            displayName: Annual Summary
            uriParameters:
              taxYear:
                description: The tax year the data applies to
                type: string
                example: 2016-17
            put:
              displayName: Update a FHL UK property business annual summary
              description: Update a FHL UK property business annual summary for a tax year
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/UK_PROP_FHL_AnnualSummary.json
                  example: !include examples/uk-properties/fhl/AnnualSummary.json
              responses:
                204:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidTaxYear:
                          description: Invalid taxYear
                          value:
                            code: TAX_YEAR_INVALID
                        invalidMonetaryAmount:
                          description: adjustments or allowances is not a non-negative amount or up to 2 decimal places
                          value:
                            code: INVALID_MONETARY_AMOUNT
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
            get:
              displayName: Get a FHL UK property business annual summary
              description: Get a FHL UK property business annual summary for a tax year
              (annotations.sandboxData): !include scenarios/agent-scenarios.md
              is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
              (annotations.scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      type: !include schemas/UK_PROP_FHL_AnnualSummary.json
                      example: !include examples/uk-properties/fhl/AnnualSummary.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        invalidNino:
                          description: Invalid NINO
                          value:
                            code: NINO_INVALID
                        invalidTaxYear:
                          description: Invalid taxYear
                          value:
                            code: TAX_YEAR_INVALID
                404:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        notFound:
                          description: Not Found
                          value:
                            code: NOT_FOUND
    /dividends:
      (annotations.group):
        name: Dividends income
        description: !include docs/dividends-income.md
      /{taxYear}:
        displayName: Annual Summary
        uriParameters:
          taxYear:
            description: The tax year the data applies to
            type: string
            example: 2016-17
        put:
          displayName: Update a dividends income annual summary
          description: Update a dividends income annual summary for a tax year
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          body:
            application/json:
              type: !include schemas/DIV_AnnualSummary.json
              example: !include examples/dividends/AnnualSummary.json
          responses:
            204:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID
                    invalidTaxYear:
                      description: Invalid taxYear
                      value:
                        code: TAX_YEAR_INVALID
                    invalidMonetaryAmount:
                      description: ukDividends is not a non-negative amount or up to 2 decimal places
                      value:
                        code: INVALID_MONETARY_AMOUNT
        get:
          displayName: Get dividends income annual summary
          description: Get dividends income for a tax year
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/DIV_AnnualSummary.json
                  example: !include examples/dividends/AnnualSummary.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID
                    invalidTaxYear:
                      description: Invalid taxYear
                      value:
                        code: TAX_YEAR_INVALID
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: Not Found
                      value:
                        code: NOT_FOUND
    /savings-accounts:
      (annotations.group):
        name: Savings accounts
        description: !include docs/savings-accounts.md
      post:
        displayName: Add a savings account
        description: Add a savings account
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "write:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
        body:
          application/json:
            type: !include schemas/SavingsAccount_Without_ID.json
            example: !include examples/savings-accounts/SavingsAccount.json
        responses:
          201:
            headers:
              Location:
                example: /self-assessment/ni/{nino}/savings-accounts/{savingsAccountId}
                description: Location of the resource created
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
                  invalidLength:
                    description: accountName length is invalid
                    value:
                      code: INVALID_FIELD_LENGTH
                  invalidValue:
                    description: accountName is not alphanumeric
                    value:
                      code: INVALID_VALUE
      get:
        displayName: List all savings accounts
        description: List all savings accounts
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "read:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include schemas/SavingsAccounts.json
                example: !include examples/savings-accounts/SavingsAccounts.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
      /{savingsAccountId}:
        put:
          displayName: Update a savings account
          description: Update a savings account
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          body:
            application/json:
              type: !include schemas/SavingsAccount_Without_ID.json
              example: !include examples/savings-accounts/SavingsAccount.json
          responses:
            204:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID
                    invalidLength:
                      description: accountName length is invalid
                      value:
                        code: INVALID_FIELD_LENGTH
                    invalidValue:
                      description: accountName is not alphanumeric
                      value:
                        code: INVALID_VALUE
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: Not Found
                      value:
                        code: NOT_FOUND
        get:
          displayName: Get a savings account
          description: Get a savings account
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/SavingsAccount_Without_ID.json
                  example: !include examples/savings-accounts/SavingsAccount.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: Not Found
                      value:
                        code: NOT_FOUND
        /{taxYear}:
          put:
            displayName: Update a savings account annual summary
            description: Update a savings account annual summary for a given tax year
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/SavingsAccount_AnnualSummary.json
                example: !include examples/savings-accounts/AnnualSummary.json
            responses:
              204:
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      invalidTaxYear:
                        description: Invalid taxYear
                        value:
                          code: TAX_YEAR_INVALID
                      invalidAmount:
                        description: taxedUkInterest is not a non-negative amount or up to 2 decimal places
                        value:
                          code: INVALID_MONETARY_AMOUNT
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
          get:
            displayName: Get a savings account annual summary
            description: Get a savings account annual summary for a given tax year
            (annotations.sandboxData): !include scenarios/agent-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/SavingsAccount_AnnualSummary.json
                    example: !include examples/savings-accounts/AnnualSummary.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      invalidTaxYear:
                        description: Invalid taxYear
                        value:
                          code: TAX_YEAR_INVALID
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: Not Found
                        value:
                          code: NOT_FOUND
    /calculations:
      (annotations.group):
        name: Tax calculations
        description: !include docs/tax-calculation.md
      post:
        displayName: Trigger a tax calculation
        description: Trigger a tax calculation
        (annotations.sandboxData): !include scenarios/agent-scenarios.md
        is: [headers.acceptHeader, contentType, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
        (annotations.scope): "write:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
        responses:
          202:
            headers:
              Location:
                example: /self-assessment/ni/{nino}/calculations/{calculationId}
                description: Location of the calculation result
            body:
              application/json:
                type: !include schemas/TaxCalculationETA.json
                example: !include examples/calculation/TaxCalculationETA.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid NINO
                    value:
                      code: NINO_INVALID
      /{taxCalculationId}:
        uriParameters:
          taxCalculationId:
            description: The ID of the tax calculation
            type: string
        get:
          displayName: Retrieve a tax calculation
          description: Retrieve a tax calculation
          (annotations.sandboxData): !include scenarios/agent-scenarios.md
          is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
          (annotations.scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/TaxCalculation.json
                  example: !include examples/calculation/TaxCalculation.json
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: Not Found
                      value:
                        code: NOT_FOUND
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: Invalid NINO
                      value:
                        code: NINO_INVALID