#%RAML 1.0
---

title: Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml

annotationTypes:
  config: object
  group:
    type: object
    properties:
      name: string
      description: string
  scope:

#
# TAXPAYER
#
/self-assessment:
  (group):
    name: Taxpayer
    description: !include docs/taxpayer.md
  get:
    displayName: Resolve taxpayer
    description: This endpoint resolves the Taxpayer identifier from the provided Authorisation Bearer token
    is: [headers.acceptHeader]
    (scope): "read:self-assessment"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
    responses:
      200:
        body:
          application/json:
            examples:
              example-1:
                value: !include examples/resolve-taxpayer-example-1.json
  /{utr}:
    uriParameters:
      utr:
        description: The Self Assessment UTR of the customer
        type: string
    get:
      displayName: Discover tax years
      description: This endpoint provides links to the self assessment entry points for each tax year
      is: [headers.acceptHeader]
      (scope): "read:self-assessment"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/discover-tax-years-example-1.json
    /{taxYear}:
      uriParameters:
        taxYear:
          description: The tax year the data applies to
          type: string
          example: ""
      get:
        displayName: Discover tax year
        description: This endpoint provides links to the self assessment entry points for the specified tax year
        is: [headers.acceptHeader]
        (scope): "read:self-assessment"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/discover-tax-year-example-1.json

#
# SELF EMPLOYMENT
#
      /self-employments:
        (group):
          name: Self employment
          description: !include docs/self-employment.md
        get:
          displayName: Get all self employments
          description: This endpoint retrieves all the Self Employments sources of income
          is: [headers.acceptHeader]
          (scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/retrieve-all-self-employments-example-1.json
        post:
          displayName: Create self employment
          description: This endpoint creates a Self Employments source of income
          is: [headers.acceptHeader, headers.contentHeader]
          (scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          body:
            application/json:
              type: !include schemas/self-employments-request.json
              example: !include examples/self-employment-request.json
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/create-self-employments-example-1.json
        /{selfEmploymentId}:
          uriParameters:
            selfEmploymentId:
              description: The self employment ID
              type: string
              example: ""
          get:
            displayName: Get self employment
            description: This endpoint retrieves a Self Employments source of income
            is: [headers.acceptHeader]
            (scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/retrieve-self-employments-example-1.json
          put:
            displayName: Update self employment
            description: This endpoint updates a Self Employments source of income
            is: [headers.acceptHeader, headers.contentHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/self-employments-request.json
                example: !include examples/self-employment-request.json
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/update-self-employments-example-1.json
          delete:
            displayName: Delete self employment
            description: This endpoint deletes a Self Employments source of income
            is: [headers.acceptHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            responses:
              204:
          /incomes:
            get:
              displayName: Get all self employments incomes
              description: This endpoint retrieves all Incomes for Self Employments
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-self-employments-incomes-example-1.json
            post:
              displayName: Create self employment income
              description: This endpoint creates a Incomes for Self Employments
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/self-employment-incomes-request.json
                  example: !include examples/self-employment-incomes-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-self-employments-incomes-example-1.json

            /{incomeId}:
              uriParameters:
                incomeId:
                  description: The income ID
                  type: string
                  example: ""
              get:
                displayName: Get self employment income
                description: This endpoint retrieves a Incomes for Self Employments
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-self-employments-incomes-example-1.json
              put:
                displayName: Update self employment income
                description: This endpoint updates a Incomes for Self Employments
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/self-employment-incomes-request.json
                    example: !include examples/self-employment-incomes-request.json

                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-self-employments-incomes-example-1.json
              delete:
                displayName: Delete self employment income
                description: This endpoint deletes a Incomes for Self Employments
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /expenses:
            get:
              displayName: Get all self employment expenses
              description: This endpoint retrieves all Expenses for Self Employments
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-self-employments-expenses-example-1.json
            post:
              displayName: Create self employment expense
              description: This endpoint creates a Expenses for Self Employments
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/self-employment-expenses-request.json
                  example: !include examples/self-employments-expenses-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-self-employments-expenses-example-1.json
            /{expenseId}:
              uriParameters:
                expenseId:
                  description: The expense ID
                  type: string
                  example: ""
              get:
                displayName: Get self employment expense
                description: This endpoint retrieves a Expenses for Self Employments
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-self-employments-expenses-example-1.json
              put:
                displayName: Update self employment expense
                description: This endpoint updates a Expenses for Self Employments
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/self-employment-expenses-request.json
                    example: !include examples/self-employments-expenses-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-self-employments-expenses-example-1.json
              delete:
                displayName: Delete self employment expense
                description: This endpoint deletes a Expenses for Self Employments
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /goods-and-services-own-uses:
            get:
              displayName: Get all self employment goods and services own uses
              description: This endpoint retrieves all Goods and Services Own Uses for Self Employments
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-self-employments-goods-and-services-own-uses-example-1.json
            post:
              displayName: Create self employment goods and services own use
              description: This endpoint creates a Goods and Services Own Uses for Self Employments
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/self-employment-own-uses-request.json
                  example: !include examples/self-employments-own-uses-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-self-employments-goods-and-services-own-uses-example-1.json
            /{goodsAndServicesOwnUseId}:
              uriParameters:
                goodsAndServicesOwnUseId:
                  description: The goods and services own use ID
                  type: string
                  example: ""
              get:
                displayName: Get self employment goods and services own use
                description: This endpoint retrieves a Goods and Services Own Uses for Self Employments
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-self-employments-goods-and-services-own-uses-example-1.json
              put:
                displayName: Update self employment goods and services own use
                description: This endpoint updates a Goods and Services Own Uses for Self Employments
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/self-employment-own-uses-request.json
                    example: !include examples/self-employments-own-uses-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-self-employments-goods-and-services-own-uses-example-1.json
              delete:
                displayName: Delete self employment goods and services own use
                description: This endpoint deletes a Goods and Services Own Uses for Self Employments
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /balancing-charges:
            get:
              displayName: Get all self employment balancing charges
              description: This endpoint retrieves all Balancing Charges for Self Employments
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-self-employments-balancing-charges-example-1.json
            post:
              displayName: Create self employment balancing charge
              description: This endpoint creates a Balancing Charges for Self Employments
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/self-employments-balancing-charges-request.json
                  example: !include examples/self-employments-balancing-charges-request.xml
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-self-employments-balancing-charges-example-1.json
            /{balancingChargeId}:
              uriParameters:
                balancingChargeId:
                  description: The balancing charge ID
                  type: string
                  example: ""
              get:
                displayName: Get self employment balancing charge
                description: This endpoint retrieves a Balancing Charges for Self Employments
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-self-employments-balancing-charges-example-1.json
              put:
                displayName: Update self employment balancing charge
                description: This endpoint updates a Balancing Charges for Self Employments
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/self-employments-balancing-charges-request.json
                    example: !include examples/self-employments-balancing-charges-request.xml
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-self-employments-balancing-charges-example-1.json
              delete:
                displayName: Delete self employment balancing charge
                description: This endpoint deletes a Balancing Charges for Self Employments
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:

#
# UK PROPERTY
#
      /uk-properties:
        (group):
          name: UK property
          description: !include docs/uk-property.md
        get:
          displayName: Get all UK properties
          description: This endpoint retrieves all the UK Properties sources of income
          is: [headers.acceptHeader]
          (scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/retrieve-all-uk-properties-example-1.json
        post:
          displayName: Create UK property
          description: This endpoint creates a UK Properties source of income
          is: [headers.acceptHeader, headers.contentHeader]
          (scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          body:
            application/json:
              type: !include schemas/uk-properties-request.json
              example: !include examples/uk-properties-request.json
          responses:
            201:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/create-uk-properties-example-1.json
        /{ukPropertyId}:
          uriParameters:
            ukPropertyId:
              description: The UK property ID
              type: string
              example: ""
          get:
            displayName: Get UK property
            description: This endpoint retrieves a UK Properties source of income
            is: [headers.acceptHeader]
            (scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/retrieve-uk-properties-example-1.json
          put:
            displayName: Update UK property
            description: This endpoint updates a UK Properties source of income
            is: [headers.acceptHeader, headers.contentHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/uk-properties-request.json
                example: !include examples/uk-properties-request.json
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/update-uk-properties-example-1.json
          delete:
            displayName: Delete UK property
            description: This endpoint deletes a UK Properties source of income
            is: [headers.acceptHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            responses:
              204:
          /taxes-paid:
            get:
              displayName: Get all UK properties taxes paid
              description: This endpoint retrieves all Taxes Paid for UK Properties
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-uk-properties-taxes-paid-example-1.json
            post:
              displayName: Create UK property taxes paid
              description: This endpoint creates a Taxes Paid for UK Properties
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/uk-properties-taxes-paid-request.json
                  example: !include examples/uk-properties-taxes-paid-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-uk-properties-taxes-paid-example-1.json
            /{taxesPaidId}:
              uriParameters:
                taxesPaidId:
                  description: The taxes paid ID
                  type: string
                  example: ""
              get:
                displayName: Get UK property taxes paid
                description: This endpoint retrieves a Taxes Paid for UK Properties
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-uk-properties-taxes-paid-example-1.json
              put:
                displayName: Update UK property taxes paid
                description: This endpoint updates a Taxes Paid for UK Properties
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/uk-properties-taxes-paid-request.json
                    example: !include examples/uk-properties-taxes-paid-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-uk-properties-taxes-paid-example-1.json
              delete:
                displayName: Delete UK property taxes paid
                description: This endpoint deletes a Taxes Paid for UK Properties
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /incomes:
            get:
              displayName: Get all UK property incomes
              description: This endpoint retrieves all Incomes for UK Properties
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-uk-properties-incomes-example-1.json
            post:
              displayName: Create UK property income
              description: This endpoint creates a Incomes for UK Properties
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/uk-properties-incomes-request.json
                  example: !include examples/uk-properties-incomes-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-uk-properties-incomes-example-1.json
            /{incomeId}:
              uriParameters:
                incomeId:
                  description: The income ID
                  type: string
                  example: ""
              get:
                displayName: Get UK property income
                description: This endpoint retrieves a Incomes for UK Properties
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-uk-properties-incomes-example-1.json
              put:
                displayName: Update UK property income
                description: This endpoint updates a Incomes for UK Properties
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/uk-properties-incomes-request.json
                    example: !include examples/uk-properties-incomes-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-uk-properties-incomes-example-1.json
              delete:
                displayName: Delete UK property income
                description: This endpoint deletes a Incomes for UK Properties
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /expenses:
            get:
              displayName: Get all UK property expenses
              description: This endpoint retrieves all Expenses for UK Properties
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-uk-properties-expenses-example-1.json
            post:
              displayName: Create UK property expense
              description: This endpoint creates a Expenses for UK Properties
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/uk-properties-expenses-request.json
                  example: !include examples/uk-properties-expenses-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-uk-properties-expenses-example-1.json
            /{expenseId}:
              uriParameters:
                expenseId:
                  description: The expense ID
                  type: string
                  example: ""
              get:
                displayName: Get UK property expense
                description: This endpoint retrieves a Expenses for UK Properties
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-uk-properties-expenses-example-1.json
              put:
                displayName: Update UK property expense
                description: This endpoint updates a Expenses for UK Properties
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/uk-properties-expenses-request.json
                    example: !include examples/uk-properties-expenses-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-uk-properties-expenses-example-1.json
              delete:
                displayName: Delete UK property expense
                description: This endpoint deletes a Expenses for UK Properties
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /private-use-adjustments:
            get:
              displayName: Get all UK property private use adjustments
              description: This endpoint retrieves all Private Use Adjustments for UK Properties
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-uk-properties-private-use-adjustments-example-1.json
            post:
              displayName: Create UK property private use adjustment
              description: This endpoint creates a Private Use Adjustments for UK Properties
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/uk-properties-private-use-request.json
                  example: !include examples/uk-properties-private-use-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-uk-properties-private-use-adjustments-example-1.json
            /{privateUseAdjustmentId}:
              uriParameters:
                privateUseAdjustmentId:
                  description: The private use adjustment ID
                  type: string
                  example: ""
              get:
                displayName: Get UK property private use adjustment
                description: This endpoint retrieves a Private Use Adjustments for UK Properties
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-uk-properties-private-use-adjustments-example-1.json
              put:
                displayName: Update UK property private use adjustment
                description: This endpoint updates a Private Use Adjustments for UK Properties
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/uk-properties-private-use-request.json
                    example: !include examples/uk-properties-private-use-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-uk-properties-private-use-adjustments-example-1.json
              delete:
                displayName: Delete UK property private use adjustment
                description: This endpoint deletes a Private Use Adjustments for UK Properties
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /balancing-charges:
            get:
              displayName: Get all UK property balancing charges
              description: This endpoint retrieves all Balancing Charges for UK Properties
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-uk-properties-balancing-charges-example-1.json
            post:
              displayName: Create UK property balancing charge
              description: This endpoint creates a Balancing Charges for UK Properties
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/uk-properties-balancing-charges-request.json
                  example: !include examples/uk-properties-balancing-charges-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-uk-properties-balancing-charges-example-1.json
            /{balancingChargeId}:
              uriParameters:
                balancingChargeId:
                  description: The balancing charge ID
                  type: string
                  example: ""
              get:
                displayName: Get UK property balancing charge
                description: This endpoint retrieves a Balancing Charges for UK Properties
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-uk-properties-balancing-charges-example-1.json
              put:
                displayName: Update UK property balancing charge
                description: This endpoint updates a Balancing Charges for UK Properties
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/uk-properties-balancing-charges-request.json
                    example: !include examples/uk-properties-balancing-charges-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-uk-properties-balancing-charges-example-1.json
              delete:
                displayName: Delete UK property balancing charge
                description: This endpoint deletes a Balancing Charges for UK Properties
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:

#
# FURNISHED HOLIDAY LETTINGS
#

      /furnished-holiday-lettings:
        (group):
          name: Furnished holiday lettings
          description: !include docs/furnished-holiday-lettings.md
        get:
          displayName: Get all furnished holiday lettings
          description: This endpoint retrieves all the Furnished Holiday Lettings sources of income
          is: [headers.acceptHeader]
          (scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/retrieve-all-furnished-holiday-lettings-example-1.json
        post:
          displayName: Create furnished holiday letting
          description: This endpoint creates a Furnished Holiday Lettings source of income
          is: [headers.acceptHeader, headers.contentHeader]
          (scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          responses:
            201:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/create-furnished-holiday-lettings-example-1.json
        /{furnishedHolidayLettingId}:
          uriParameters:
            furnishedHolidayLettingId:
              description: The furnished holiday letting ID
              type: string
              example: ""
          get:
            displayName: Get furnished holiday letting
            description: This endpoint retrieves a Furnished Holiday Lettings source of income
            is: [headers.acceptHeader]
            (scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/retrieve-furnished-holiday-lettings-example-1.json
          put:
            displayName: Update furnished holiday letting
            description: This endpoint updates a Furnished Holiday Lettings source of income
            is: [headers.acceptHeader, headers.contentHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            body:
              application/json:
                type: !include schemas/furnished-holiday-lettings-request.json
                example: !include examples/furnished-holiday-lettings-request.json
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/update-furnished-holiday-lettings-example-1.json
          delete:
            displayName: Delete furnished holiday letting
            description: This endpoint deletes a Furnished Holiday Lettings source of income
            is: [headers.acceptHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            responses:
              204:
          /incomes:
            get:
              displayName: Get all furnished holiday letting incomes
              description: This endpoint retrieves all Incomes for Furnished Holiday Lettings
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-furnished-holiday-lettings-incomes-example-1.json
            post:
              displayName: Create furnished holiday letting income
              description: This endpoint creates a Incomes for Furnished Holiday Lettings
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/furnished-holiday-lettings-incomes-request.json
                  example: !include examples/furnished-holiday-lettings-incomes-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-furnished-holiday-lettings-incomes-example-1.json
            /{incomeId}:
              uriParameters:
                incomeId:
                  description: The income ID
                  type: string
                  example: ""
              get:
                displayName: Get furnished holiday letting income
                description: This endpoint retrieves a Incomes for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-furnished-holiday-lettings-incomes-example-1.json
              put:
                displayName: Update furnished holiday letting income
                description: This endpoint updates a Incomes for Furnished Holiday Lettings
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/furnished-holiday-lettings-incomes-request.json
                    example: !include examples/furnished-holiday-lettings-incomes-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-furnished-holiday-lettings-incomes-example-1.json
              delete:
                displayName: Delete furnished holiday letting income
                description: This endpoint deletes a Incomes for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /expenses:
            get:
              displayName: Get all furnished holiday letting expenses
              description: This endpoint retrieves all Expenses for Furnished Holiday Lettings
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-furnished-holiday-lettings-expenses-example-1.json
            post:
              displayName: Create furnished holiday letting expense
              description: This endpoint creates a Expenses for Furnished Holiday Lettings
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/furnished-holiday-lettings-expenses-request.json
                  example: !include examples/furnished-holiday-lettings-expenses-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-furnished-holiday-lettings-expenses-example-1.json
            /{expenseId}:
              uriParameters:
                expenseId:
                  description: The expense ID
                  type: string
                  example: ""
              get:
                displayName: Get furnished holiday letting expense
                description: This endpoint retrieves a Expenses for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-furnished-holiday-lettings-expenses-example-1.json
              put:
                displayName: Update furnished holiday letting expense
                description: This endpoint updates a Expenses for Furnished Holiday Lettings
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/furnished-holiday-lettings-expenses-request.json
                    example: !include examples/furnished-holiday-lettings-expenses-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-furnished-holiday-lettings-expenses-example-1.json
              delete:
                displayName: Delete furnished holiday letting expense
                description: This endpoint deletes a Expenses for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /private-use-adjustments:
            get:
              displayName: Get all furnished holiday letting private use adjustments
              description: This endpoint retrieves all Private Use Adjustments for Furnished Holiday Lettings
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-furnished-holiday-lettings-private-use-adjustments-example-1.json
            post:
              displayName: Create furnished holiday letting private use adjustment
              description: This endpoint creates a Private Use Adjustments for Furnished Holiday Lettings
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/furnished-holiday-lettings-private-use-request.json
                  example: !include examples/furnished-holiday-lettings-private-use-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-furnished-holiday-lettings-private-use-adjustments-example-1.json
            /{privateUseAdjustmentId}:
              uriParameters:
                privateUseAdjustmentId:
                  description: The private use adjustment ID
                  type: string
                  example: ""
              get:
                displayName: Get furnished holiday letting private use adjustment
                description: This endpoint retrieves a Private Use Adjustments for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-furnished-holiday-lettings-private-use-adjustments-example-1.json
              put:
                displayName: Update furnished holiday letting private use adjustment
                description: This endpoint updates a Private Use Adjustments for Furnished Holiday Lettings
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/furnished-holiday-lettings-private-use-request.json
                    example: !include examples/furnished-holiday-lettings-private-use-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-furnished-holiday-lettings-private-use-adjustments-example-1.json
              delete:
                displayName: Delete furnished holiday letting private use adjustment
                description: This endpoint deletes a Private Use Adjustments for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /balancing-charges:
            get:
              displayName: Get all furnished holiday letting balancing charges
              description: This endpoint retrieves all Balancing Charges for Furnished Holiday Lettings
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-furnished-holiday-lettings-balancing-charges-example-1.json
            post:
              displayName: Create furnished holiday letting balancing charge
              description: This endpoint creates a Balancing Charges for Furnished Holiday Lettings
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/furnished-holiday-lettings-balancing-charges-request.json
                  example: !include examples/furnished-holiday-lettings-balancing-charges-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-furnished-holiday-lettings-balancing-charges-example-1.json
            /{balancingChargeId}:
              uriParameters:
                balancingChargeId:
                  description: The balancing charge ID
                  type: string
                  example: ""
              get:
                displayName: Get furnished holiday letting balancing charge
                description: This endpoint retrieves a Balancing Charges for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-furnished-holiday-lettings-balancing-charges-example-1.json
              put:
                displayName: Update furnished holiday lettings balancing charge
                description: This endpoint updates a Balancing Charges for Furnished Holiday Lettings
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/furnished-holiday-lettings-balancing-charges-request.json
                    example: !include examples/furnished-holiday-lettings-balancing-charges-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-furnished-holiday-lettings-balancing-charges-example-1.json
              delete:
                displayName: Delete furnished holiday letting balancing charge
                description: This endpoint deletes a Balancing Charges for Furnished Holiday Lettings
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:

#
# UNEARNED INCOME
#
      /unearned-incomes:
        (group):
          name: Unearned income
          description: !include docs/unearned-income.md
        get:
          displayName: Get all unearned incomes
          description: This endpoint retrieves all the Unearned Incomes sources of income
          is: [headers.acceptHeader]
          (scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/retrieve-all-unearned-incomes-example-1.json
        post:
          displayName: Create unearned income
          description: This endpoint creates a Unearned Incomes source of income
          is: [headers.acceptHeader, headers.contentHeader]
          (scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          responses:
            201:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/create-unearned-incomes-example-1.json
        /{unearnedIncomeId}:
          uriParameters:
            unearnedIncomeId:
              description: The unearned income ID
              type: string
              example: ""
          get:
            displayName: Get unearned income
            description: This endpoint retrieves a Unearned Incomes source of income
            is: [headers.acceptHeader]
            (scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/retrieve-unearned-incomes-example-1.json
          delete:
            displayName: Delete unearned income
            description: This endpoint deletes a Unearned Incomes source of income
            is: [headers.acceptHeader]
            (scope): "write:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
            responses:
              204:
          /savings:
            get:
              displayName: Get all unearned income savings
              description: This endpoint retrieves all Savings for Unearned Incomes
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-unearned-incomes-savings-example-1.json
            post:
              displayName: Create unearned income saving
              description: This endpoint creates a Savings for Unearned Incomes
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/unearned-incomes-savings-request.json
                  example: !include examples/unearned-incomes-savings-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-unearned-incomes-savings-example-1.json
            /{savingId}:
              uriParameters:
                savingId:
                  description: The saving ID
                  type: string
                  example: ""
              get:
                displayName: Get unearned income saving
                description: This endpoint retrieves a Savings for Unearned Incomes
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-unearned-incomes-savings-example-1.json
              put:
                displayName: Update unearned income saving
                description: This endpoint updates a Savings for Unearned Incomes
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/unearned-incomes-savings-request.json
                    example: !include examples/unearned-incomes-savings-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-unearned-incomes-savings-example-1.json
              delete:
                displayName: Delete unearned income saving
                description: This endpoint deletes a Savings for Unearned Incomes
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:
          /dividends:
            get:
              displayName: Get all unearned income dividends
              description: This endpoint retrieves all Dividends for Unearned Incomes
              is: [headers.acceptHeader]
              (scope): "read:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
              responses:
                200:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/retrieve-all-unearned-incomes-dividends-example-1.json
            post:
              displayName: Create unearned income dividend
              description: This endpoint creates a Dividends for Unearned Incomes
              is: [headers.acceptHeader, headers.contentHeader]
              (scope): "write:self-assessment"
              securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
              body:
                application/json:
                  type: !include schemas/unearned-incomes-dividends-request.json
                  example: !include examples/unearned-incomes-dividends-request.json
              responses:
                201:
                  body:
                    application/json:
                      examples:
                        example-1:
                          value: !include examples/create-unearned-incomes-dividends-example-1.json
            /{dividendId}:
              uriParameters:
                dividendId:
                  description: The dividend ID
                  type: string
                  example: ""
              get:
                displayName: Get unearned income dividend
                description: This endpoint retrieves a Dividends for Unearned Incomes
                is: [headers.acceptHeader]
                (scope): "read:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/retrieve-unearned-incomes-dividends-example-1.json
              put:
                displayName: Update unearned income dividend
                description: This endpoint updates a Dividends for Unearned Incomes
                is: [headers.acceptHeader, headers.contentHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                body:
                  application/json:
                    type: !include schemas/unearned-incomes-dividends-request.json
                    example: !include examples/unearned-incomes-dividends-request.json
                responses:
                  200:
                    body:
                      application/json:
                        examples:
                          example-1:
                            value: !include examples/update-unearned-incomes-dividends-example-1.json
              delete:
                displayName: Delete unearned income dividend
                description: This endpoint deletes a Dividends for Unearned Incomes
                is: [headers.acceptHeader]
                (scope): "write:self-assessment"
                securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
                responses:
                  204:

#
# LIABILITY
#
      /liability:
        (group):
          name: Liability
          description: !include docs/liability.md
        post:
          displayName: Request liability
          description: This endpoint requests a liability estimate
          is: [headers.acceptHeader]
          (scope): "write:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
          responses:
            202:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/request-liability-example-1.json
        get:
          displayName: Get liability
          description: This endpoint retrieves a liability estimate
          is: [headers.acceptHeader]
          (scope): "read:self-assessment"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/retrieve-liability.json
                  examples:
                    example-1:
                      value: !include examples/retrieve-liability-example-1.json
